### ISSUE TITLE
Duplicated fields

### ISSUE THREAD

**Issue by laanwj** [bjoernQ/svd2html#2]
I've been using this on the generated `soc.svd` in the betrusted repo:  https://github.com/betrusted-io/xous-core/blob/main/precursors/soc.svd

It looks like every (edit: no, only the last?) field is shown twice. For example: 

![20220619_12h08m18s_grim](https://user-images.githubusercontent.com/126646/174476076-e528e1fc-c064-47b1-a026-6cd41265e872.png)

As far as I can see they're only once in the XML:
```xml
                    <fields>
                        <field>
                            <name>soc_reset</name>
                            <msb>7</msb>
                            <bitRange>[7:0]</bitRange>
                            <lsb>0</lsb>
                        </field>
                    </fields>
```

Edit: ok, looking at it some more, my guess is that the unused bits in the field are labaled in the same way as the last field encountered.

**Comment by bjoernQ** [comment]
Thanks for letting me know. I'm currently on vacation and will look into this as soon as I'm back

**Comment by bjoernQ** [comment]
Should be fixed now on `main` branch - Thanks again for reporting this issue

**Comment by laanwj** [comment]
I've retried and can confirm this is fixed. Thank you!

**Comment by bjoernQ** [comment]
Thanks a lot for the confirmation!
